# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CKANInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(default='data.wprdc.org/', verbose_name='url of ckan instance')),
                ('api_key', models.UUIDField(default=None, verbose_name='ckan api key')),
            ],
            options={
                'verbose_name': 'CKAN Instance',
            },
        ),
        migrations.CreateModel(
            name='CKANResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_id', models.UUIDField(default=None, verbose_name='resource id')),
                ('parcel_id_field', models.CharField(max_length=200, verbose_name='field name that contains parcel ID')),
                ('multi_per_pin', models.BooleanField(verbose_name='can a parcel have multiple records?')),
                ('ckan_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_api.CKANInstance')),
            ],
            options={
                'verbose_name': 'CKAN Resource',
            },
        ),
    ]
