# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckanresource',
            name='ckan_instance',
        ),
        migrations.AddField(
            model_name='ckanresource',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CKANInstance',
        ),
    ]
