# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0002_auto_20161121_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanresource',
            name='info',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
