# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0003_ckanresource_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckanresource',
            name='contains_geo',
            field=models.BooleanField(default=False, help_text='Should only be for one resource.', verbose_name='Contains coordinates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ckanresource',
            name='lat_field',
            field=models.CharField(default='', help_text='Only if field contains coordinates', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ckanresource',
            name='lon_field',
            field=models.CharField(default='', help_text='Only if field contains coordinates', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ckanresource',
            name='multi_per_pin',
            field=models.BooleanField(verbose_name='Parcel can have multiple records'),
        ),
        migrations.AlterField(
            model_name='ckanresource',
            name='parcel_id_field',
            field=models.CharField(max_length=200, verbose_name='Parcel ID field (e.g. PARID)'),
        ),
        migrations.AlterField(
            model_name='ckanresource',
            name='resource_id',
            field=models.UUIDField(default=None, verbose_name='Resource ID'),
        ),
    ]
