# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0005_auto_20161121_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanresource',
            name='lat_field',
            field=models.CharField(blank=True, help_text='Only if field contains coordinates', max_length=20),
        ),
        migrations.AlterField(
            model_name='ckanresource',
            name='lon_field',
            field=models.CharField(blank=True, help_text='Only if field contains coordinates', max_length=20),
        ),
    ]
