# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0008_auto_20170601_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckanresource',
            name='resource_id',
            field=models.UUIDField(default=None, verbose_name='Resource ID'),
        ),
    ]
